[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Branch deploy previews
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"